const DEFAULT_SHOWN_COMMENTS = 5;
const MAX_AVAILABLE_HASHTAGS = 5;
const MAX_COMMENT_WORDS = 140;
const SCALE_IMAGE_DEFAULT = 100;
const SCALE_IMAGE_STEP = 25;
const SCALE_IMAGE_MAX = 100;
const SCALE_IMAGE_MIN = 25;

export {
  DEFAULT_SHOWN_COMMENTS,
  MAX_AVAILABLE_HASHTAGS,
  MAX_COMMENT_WORDS,
  SCALE_IMAGE_MAX,
  SCALE_IMAGE_MIN,
  SCALE_IMAGE_STEP,
  SCALE_IMAGE_DEFAULT
};
